export const keywordData = [
  { keyword: "ETF", isChecked: true },
  { keyword: "News", isChecked: true },
  { keyword: "Money", isChecked: false },
  { keyword: "ETF", isChecked: true },
  { keyword: "News", isChecked: true },
  { keyword: "Money", isChecked: true },
  { keyword: "ETF", isChecked: false },
  { keyword: "News", isChecked: true },
  { keyword: "Money", isChecked: true },
  { keyword: "ETF", isChecked: true },
  { keyword: "News", isChecked: true },
  { keyword: "Money", isChecked: false },
  { keyword: "ETF", isChecked: true },
  { keyword: "News", isChecked: true },
  { keyword: "News", isChecked: true },
  { keyword: "News", isChecked: true },
  { keyword: "News", isChecked: true },
  { keyword: "News", isChecked: true },
  { keyword: "News", isChecked: true },
  { keyword: "News", isChecked: true },
];
